import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'
import { canManageDevices, canUseTools } from '../company/src/access.js'
import { authenticateRequest, bearerToken } from '../api/_lib/companyLicensing.js'
import { capabilitiesFor, deriveLicenseState, effectiveEntitlement, enrollmentPayload, membershipAllowed, normalizePlate, publicDevice, validateInspectionInput } from '../api/_lib/companyLicensingCore.js'
import { canonicalDeviceRequest, validateDeviceHeaders } from '../api/_lib/deviceAuthentication.js'
import { inspectionListQuery, publicInspection } from '../api/_lib/companyInspections.js'

const now = new Date('2026-08-16T12:00:00.000Z')
const organization = { id: 'org', status: 'active' }
const license = (overrides = {}) => ({ id: 'license', kind: 'trial', status: 'active', capacity: 10, starts_at: '2026-08-01T00:00:00Z', ends_at: '2026-09-15T00:00:00Z', ...overrides })

test('missing JWT is rejected with 401', async () => { assert.equal(bearerToken({ headers: {} }), null); await assert.rejects(authenticateRequest({ headers: {} }, {}), (error) => error.status === 401) })
test('invalid JWT is rejected with 401', async () => { const clients = { dto: { auth: { getUser: async () => ({ data: { user: null }, error: new Error('bad jwt') }) } } }; await assert.rejects(authenticateRequest({ headers: { authorization: 'Bearer invalid' } }, clients), (error) => error.status === 401) })
test('missing and revoked memberships are denied', () => { assert.equal(membershipAllowed(null), false); assert.equal(membershipAllowed({ role: 'COMPANY_ADMIN', status: 'revoked' }), false); assert.equal(membershipAllowed({ role: 'COMPANY_ADMIN', status: 'active' }), true) })
test('valid trial and commercial licenses honor status and dates', () => { assert.equal(deriveLicenseState(organization, [license()], now).state, 'active_trial'); assert.equal(deriveLicenseState(organization, [license({ kind: 'commercial' })], now).state, 'active_license') })
test('expired, suspended, future and revoked licenses fail closed', () => { for (const [expected, value] of [['expired', license({ ends_at: '2026-08-15T00:00:00Z' })], ['license_suspended', license({ status: 'suspended' })], ['not_started', license({ starts_at: '2026-08-20T00:00:00Z' })], ['revoked', license({ status: 'revoked' })]]) assert.equal(deriveLicenseState(organization, [value], now).state, expected) })
test('closed and suspended organizations fail closed', () => { assert.equal(deriveLicenseState({ status: 'closed' }, [license()], now).valid, false); assert.equal(deriveLicenseState({ status: 'suspended' }, [license()], now).state, 'organization_suspended') })
test('role capabilities keep operators and guests away from devices', () => { assert.equal(capabilitiesFor('COMPANY_ADMIN', true).manageDevices, true); assert.equal(capabilitiesFor('COMPANY_OPERATOR', true).manageDevices, false); assert.equal(capabilitiesFor('UNION_GUEST', true).manageDevices, false); assert.equal(canUseTools({ capabilities: { useTools: true } }), true); assert.equal(canManageDevices({ capabilities: { manageDevices: false } }), false); assert.equal(canUseTools(null), false) })
test('founder and tester grants bypass payment without enabling personal mode', () => { assert.equal(effectiveEntitlement({ valid: false }, [{ grant_type: 'FOUNDER', product_mode: 'company', status: 'active', starts_at: '2026-01-01' }], now).source, 'founder'); assert.equal(effectiveEntitlement({ valid: false }, [{ grant_type: 'TESTER', status: 'revoked' }], now).valid, false); assert.equal(effectiveEntitlement({ valid: true, license: { kind: 'commercial', product_mode: 'personal' } }, [], now).cloudEnabled, false) })
test('inspection input is normalized and bounded', () => { assert.equal(normalizePlate(' ab-123 cd '), 'AB123CD'); assert.equal(validateInspectionInput({ inspectionType: 'pickup', vehiclePlate: 'AB123CD', inspectedAt: '2026-08-20T10:00:00.000Z', documentHash: 'a'.repeat(64), documentSizeBytes: 18 * 1024 * 1024, deviceGeneratedId: '12345678-1234-1234-1234-123456789abc' }), null) })
test('device request requires complete fresh anti-replay headers', () => { const request = { method: 'POST', url: '/api/device-inspection-finalize', headers: { 'x-checkvan-device-id': 'd', 'x-checkvan-key-id': 'k', 'x-checkvan-request-id': 'r', 'x-checkvan-signature': 's', 'x-checkvan-timestamp': '2026-08-20T10:00:00.000Z' }, body: { inspectionId: 'i' } }; assert.equal(validateDeviceHeaders(request, Date.parse('2026-08-20T10:01:00Z')).error, undefined); assert.match(canonicalDeviceRequest(request, request.body), /^POST\n\/api\/device-inspection-finalize\n/) })

test('device canonical request can use the trusted public gateway path after a Vercel rewrite', () => {
  const request = { method: 'POST', url: '/api/platform?resource=device-vehicles', headers: { 'x-checkvan-request-id': 'r', 'x-checkvan-timestamp': '2026-08-23T10:00:00.000Z' } }
  assert.match(canonicalDeviceRequest(request, {}, '/api/device-vehicles'), /^POST\n\/api\/device-vehicles\n/)
})
test('inspection queries clamp pagination and public output hides storage paths', () => { const query = inspectionListQuery({ limit: '999', plate: ' ab-123 ' }); assert.equal(query.limit, 100); assert.equal(query.plate, 'AB123'); const result = publicInspection({ id: 'i', inspection_type: 'pickup', vehicle_plate: 'AB', storage_object_path: 'secret' }); assert.equal(JSON.stringify(result).includes('secret'), false) })
test('device response excludes cryptographic material', () => { const result = publicDevice({ status: 'active', assigned_at: 'a', released_at: null }, { id: 'd', last_validated_at: 'v', public_key_spki_base64: 'secret', key_id: 'secret' }, 0); assert.deepEqual(Object.keys(result), ['id', 'label', 'status', 'assignedAt', 'lastValidatedAt', 'releasedAt']); assert.equal(JSON.stringify(result).includes('secret'), false) })
test('QR payload is exactly versioned and contains the same manual token', () => { const token = 'A'.repeat(43); assert.equal(enrollmentPayload(token), `checkvan-enroll:v1:${token}`) })
test('membership migration has constraints, RLS and server-only grants', async () => { const sql = await readFile(new URL('../supabase/checkvan-migrations/20260816162608_create_checkvan_area_memberships.sql', import.meta.url), 'utf8'); assert.match(sql, /unique \(auth_subject\)/i); assert.match(sql, /enable row level security/i); assert.match(sql, /revoke all.*anon, authenticated/i); assert.match(sql, /grant select, insert, update, delete.*service_role/i); assert.doesNotMatch(sql, /references auth\.users/i) })
test('enrollment endpoint uses the real admin RPC, 24 hours and no cache helper', async () => { const source = await readFile(new URL('../api/company-enrollment-token.js', import.meta.url), 'utf8'); assert.match(source, /24 \* 60 \* 60 \* 1000/); assert.match(source, /admin_create_checkvan_enrollment_token/); assert.match(source, /manageDevices/); assert.doesNotMatch(source, /console\.|localStorage|service_role/i) })
test('closing activation removes token and QR from UI memory', async () => { const source = await readFile(new URL('../company/src/pages/DevicesPage.jsx', import.meta.url), 'utf8'); assert.match(source, /closeActivation.*setActivation\(null\).*setQr\(''\)/s); assert.doesNotMatch(source, /localStorage|sessionStorage/) })
test('browser source never references the service role variable', async () => { const sources = await Promise.all(['../company/src/lib/companySupabase.js', '../company/src/auth/AuthContext.jsx'].map((path) => readFile(new URL(path, import.meta.url), 'utf8'))); assert.doesNotMatch(sources.join('\n'), /CHECKVAN_SUPABASE_SERVICE_ROLE_KEY|service_role/i) })
test('cloud migration keeps storage private and personal commercially disabled', async () => { const sql = await readFile(new URL('../supabase/checkvan-migrations/20260820120000_create_company_cloud_platform.sql', import.meta.url), 'utf8'); assert.match(sql, /checkvan-company-inspections.*false/s); assert.match(sql, /product_mode.*company.*personal/i); assert.match(sql, /check \(product_mode = 'company'\)/i); assert.match(sql, /enable row level security/i); assert.doesNotMatch(sql, /grant .* to anon/i) })
test('incremental cloud migration reuses remote founder and device-key structures', async () => { const sql = await readFile(new URL('../supabase/checkvan-migrations/20260821120000_extend_existing_checkvan_company_cloud.sql', import.meta.url), 'utf8'); assert.match(sql, /alter table public\.checkvan_founder_entitlements/i); assert.match(sql, /references public\.checkvan_founder_entitlements/i); assert.doesNotMatch(sql, /create table public\.checkvan_founder_entitlements/i); assert.doesNotMatch(sql, /create table public\.checkvan_access_entitlements/i); assert.doesNotMatch(sql, /create or replace function public\.admin_create_checkvan_enrollment_token/i); assert.doesNotMatch(sql, /insert into storage\.buckets/i) })
test('device authentication reads the normalized remote device key table', async () => { const source = await readFile(new URL('../api/_lib/deviceAuthentication.js', import.meta.url), 'utf8'); assert.match(source, /from\('checkvan_device_keys'\)/); assert.match(source, /device\.device_key_id !== key\.device_key_id/); assert.doesNotMatch(source, /checkvan_access_entitlements/) })
test('enrollment API completes the existing remote challenge flow', async () => { const sources = await Promise.all(['../api/device-enrollment-challenge.js', '../api/device-enroll.js'].map((path) => readFile(new URL(path, import.meta.url), 'utf8'))); const source = sources.join('\n'); assert.match(source, /internal_create_checkvan_challenge/); assert.match(source, /internal_get_checkvan_challenge_key/); assert.match(source, /internal_complete_checkvan_enrollment/); assert.doesNotMatch(source, /consume_checkvan_enrollment_token/) })
