import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { importableFleetRows, parseFleetCsv } from '../company/src/lib/fleetCsv.js'
import { removeVehicleOptimistically } from '../company/src/lib/fleetRemovalState.js'
import { vehicleBatchInput } from '../api/_lib/companyVehicles.js'

const migrationUrl = new URL('../supabase/migrations/20260824184757_fleet_csv_import_and_safe_vehicle_removal.sql', import.meta.url)
test('CSV valido con tutte le categorie supportate', () => { const result = parseFleetCsv('codice_mezzo,targa,categoria\nL-1,AA111AA,LARGE\nM-1,BB222BB,MEDIUM\nS-1,CC333CC,SMALL\nXS-1,DD444DD,EXTRA_SMALL'); assert.equal(result.ready, 4) })
test('CSV normalizza trim e uppercase', () => { const { rows } = parseFleetCsv('codice_mezzo,targa,categoria\n s-1 , ab 123 cd , small '); assert.deepEqual([rows[0].internal_code, rows[0].plate, rows[0].silhouette_category], ['S-1', 'AB 123 CD', 'SMALL']) })
test('CSV segnala codice duplicato interno', () => { const p = parseFleetCsv('codice_mezzo,targa,categoria\nS1,AA111AA,SMALL\ns1,BB222BB,SMALL'); assert.match(p.rows[1].errors.join(), /Codice duplicato/) })
test('CSV segnala targa duplicata interna normalizzata', () => { const p = parseFleetCsv('codice_mezzo,targa,categoria\nS1,AA-111-AA,SMALL\nS2,AA111AA,SMALL'); assert.match(p.rows[1].errors.join(), /Targa duplicata/) })
test('CSV segnala codice e targa già presenti nella stessa company', () => { const p = parseFleetCsv('codice_mezzo,targa,categoria\nS1,AA111AA,SMALL\nS2,BB222BB,SMALL', [{ internal_code: 'S1', plate: 'ZZ999ZZ' }, { internal_code: 'X', plate: 'BB-222-BB' }]); assert.match(p.rows[0].errors.join(), /Codice già presente/); assert.match(p.rows[1].errors.join(), /Targa già presente/) })
test('CSV segnala categoria invalida e riga incompleta', () => { const p = parseFleetCsv('codice_mezzo,targa,categoria\nS1,AA111AA,VAN\nS2,,SMALL'); assert.equal(p.invalid, 2); assert.match(p.rows[0].errors.join(), /Categoria non valida/); assert.match(p.rows[1].errors.join(), /Targa obbligatoria/) })
test('import parziale invia soltanto righe valide', () => { const p = parseFleetCsv('codice_mezzo,targa,categoria\nS1,AA111AA,SMALL\nS2,,SMALL'); assert.equal(importableFleetRows(p).length, 1) })
test('validazione backend batch normalizza e limita il payload', () => { assert.deepEqual(vehicleBatchInput({ vehicles: [{ internal_code: ' s1 ', plate: ' aa111aa ', silhouette_category: 'small' }] })[0].internal_code, 'S1'); assert.throws(() => vehicleBatchInput({ vehicles: [] }), /INVALID_VEHICLE_BATCH/) })
test('RPC batch è idempotente e company-scoped', async () => { const sql = await readFile(migrationUrl, 'utf8'); assert.match(sql, /pg_advisory_xact_lock/); assert.match(sql, /organization_id=p_organization_id and upper\(internal_code\)=code/); assert.match(sql, /organization_id=p_organization_id and plate_normalized=plate_key/); assert.match(sql, /COMPANY_ADMIN_REQUIRED/) })
test('RPC batch consente risultati parziali senza fallire tutto', async () => { const sql = await readFile(migrationUrl, 'utf8'); assert.match(sql, /'status','INVALID'/); assert.match(sql, /'status','IMPORTED'/); assert.match(sql, /'imported',imported,'skipped',skipped/) })
test('vehicle senza storico viene eliminato in sicurezza', async () => { const sql = await readFile(migrationUrl, 'utf8'); assert.match(sql, /if has_history then[\s\S]*end if;[\s\S]*delete from public\.checkvan_vehicles/) })
test('vehicle con storico viene archiviato e non cancellato', async () => { const sql = await readFile(migrationUrl, 'utf8'); assert.match(sql, /status='archived',archived_at=now\(\)/); assert.match(sql, /'mode','ARCHIVED'/) })
test('ispezioni danni ed eventi determinano lo storico', async () => { const sql = await readFile(migrationUrl, 'utf8'); for (const table of ['checkvan_inspections','checkvan_vehicle_damages','checkvan_vehicle_events']) assert.match(sql, new RegExp(table)) })
test('audit della rimozione è append-only', async () => { const sql = await readFile(migrationUrl, 'utf8'); assert.match(sql, /event_type in \('ARCHIVED','DELETED'\)/); assert.doesNotMatch(sql, /delete from public\.checkvan_vehicle_events/) })
test('catalogo operativo esclude archived e driver resta active-only', async () => { const platform = await readFile(new URL('../api/platform.js', import.meta.url), 'utf8'); assert.match(platform, /vehicle\.status !== 'archived'/); assert.match(platform, /eq\('status', 'active'\)/) })
test('rollback UI ripristina la flotta precedente', async () => { const vehicle = { vehicle_id: 'v1' }, original = [vehicle], states = []; await assert.rejects(removeVehicleOptimistically({ vehicle, items: original, setItems: (value) => states.push(value), setError: () => {}, request: async () => { throw new Error('fail') } })); assert.deepEqual(states, [[], original]) })
test('gateway riusa le route esistenti per batch e DELETE', async () => { const platform = await readFile(new URL('../api/platform.js', import.meta.url), 'utf8'); assert.match(platform, /request\.method === 'DELETE'/); assert.match(platform, /internal_admin_import_checkvan_vehicles/); assert.match(platform, /internal_admin_remove_checkvan_vehicle/) })
