import { createContext, useContext, useEffect, useState } from 'react'
import { NavLink, Navigate, Outlet, Route, Routes, useParams } from 'react-router-dom'
import { adminRequest, auth, configured, signInSuperAdminWithGoogle } from './lib.js'
import MfaSecurityPage from './MfaSecurityPage.jsx'
import MfaChallengePage from './MfaChallengePage.jsx'

const SessionContext = createContext(null)
const useSession = () => useContext(SessionContext)
const fmt = (value) => value ? new Intl.DateTimeFormat('it-IT', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '—'
const Badge = ({ value = '—', level }) => <span className={`badge badge--${level ?? (['active','available','ok'].includes(String(value).toLowerCase()) ? 'ok' : ['failed','error','suspended','revoked'].includes(String(value).toLowerCase()) ? 'error' : 'warning')}`}>{value}</span>

function SessionProvider({ children }) {
  const [session, setSession] = useState(null); const [admin, setAdmin] = useState(null); const [loading, setLoading] = useState(configured); const [denied, setDenied] = useState(false); const [mfaRequired,setMfaRequired]=useState(false)
  useEffect(() => { if (!auth) return undefined; let active = true
    const resolve = async (next) => { if (!active) return; setLoading(true); setSession(next); setAdmin(null); setDenied(false); setMfaRequired(false); if (!next) { setLoading(false); return } try { const data = await adminRequest(next.access_token, 'access'); if (active) setAdmin(data.admin) } catch (error) { if (active) { if (error.message === 'MFA_REQUIRED') setMfaRequired(true); else setDenied(error.status === 403) } } finally { if (active) setLoading(false) } }
    auth.auth.getSession().then(({ data }) => resolve(data.session)); const { data } = auth.auth.onAuthStateChange((_event, next) => resolve(next)); return () => { active = false; data.subscription.unsubscribe() }
  }, [])
  return <SessionContext.Provider value={{ session, admin, loading, denied, mfaRequired }}>{children}</SessionContext.Provider>
}

function Login() { const { session, admin, loading, denied, mfaRequired } = useSession(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [oauthBusy,setOauthBusy]=useState(false)
  if (loading) return <State text="Verifica accesso…"/>; if (session && mfaRequired) return <Navigate to="/super-admin/mfa" replace/>; if (session && admin) return <Navigate to="/super-admin/dashboard" replace/>
  const submit=async(e)=>{e.preventDefault();setError('');const {error:reason}=await auth.auth.signInWithPassword({email,password});if(reason)setError('Credenziali non valide.')}
  const google=async()=>{setOauthBusy(true);setError('');try{const {error:reason}=await signInSuperAdminWithGoogle();if(reason)throw reason}catch{setError('Accesso con Google non riuscito. Riprova.');setOauthBusy(false)}}
  return <main className="login"><section><img src="/brand/dto-solution-horizontal.svg" alt="DTO Solution"/><p className="kicker">Accesso riservato</p><h1>Super Admin</h1><p>Amministrazione della piattaforma DTO Solution.</p>{denied&&<p className="notice error">Account autenticato ma non autorizzato.</p>}{!configured&&<p className="notice error">Configurazione Auth mancante.</p>}<button className="google-login" type="button" disabled={!configured||oauthBusy} onClick={google}>{oauthBusy?'Reindirizzamentoâ€¦':'Continua con Google'}</button><div className="login-divider"><span>oppure</span></div><form onSubmit={submit}><label>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={!configured}>Accedi</button></form>{error&&<p className="notice error">{error}</p>}</section></main> }
function Guard(){const {session,admin,loading}=useSession();if(loading)return <State text="Verifica autorizzazione…"/>;return session&&admin?<Outlet/>:<Navigate to="/super-admin/login" replace/>}
function MfaGuard(){const {session,admin,loading,mfaRequired}=useSession();if(loading)return <State text="Verifica autorizzazione…"/>;if(session&&admin)return <Navigate to="/super-admin/dashboard" replace/>;return session&&mfaRequired?<Outlet/>:<Navigate to="/super-admin/login" replace/>}
function Shell(){return <div className="shell"><aside><NavLink className="brand" to="/super-admin/dashboard"><img src="/brand/dto-solution-horizontal-light.svg" alt="DTO Solution"/><span>Super Admin</span></NavLink><nav><NavLink to="/super-admin/dashboard">Dashboard</NavLink><NavLink to="/super-admin/aziende">Aziende</NavLink><NavLink to="/super-admin/dispositivi">Dispositivi</NavLink><NavLink to="/super-admin/sincronizzazioni">Sincronizzazioni</NavLink><NavLink to="/super-admin/audit">Audit</NavLink><NavLink to="/super-admin/sicurezza">Sicurezza account</NavLink></nav><button onClick={()=>auth.auth.signOut()}>Esci</button></aside><main><Outlet/></main></div>}
function State({text}){return <main className="state">{text}</main>}
function useResource(resource, params={}){const {session}=useSession();const [state,setState]=useState({loading:true,data:null,error:''});const key=JSON.stringify(params);useEffect(()=>{let active=true;const parsed=JSON.parse(key);adminRequest(session.access_token,resource,parsed).then(data=>active&&setState({loading:false,data,error:''})).catch(error=>active&&setState({loading:false,data:null,error:error.message}));return()=>{active=false}},[resource,key,session]);return state}
function Page({title,children}){return <section className="page"><header><p className="kicker">DTO Solution — Super Admin</p><h1>{title}</h1></header>{children}</section>}
function Load({state,children}){if(state.loading)return <State text="Caricamento…"/>;if(state.error)return <p className="notice error">Dati non disponibili: {state.error}</p>;return <>{children(state.data)}{state.data?.item?.license&&<LicenseEditor organization={state.data.item}/>}</>}

function LicenseEditor({organization}) {
  const { session } = useSession(); const license = organization.license
  const [status, setStatus] = useState(license.status); const [capacity, setCapacity] = useState(String(license.capacity)); const [endsAt, setEndsAt] = useState(license.ends_at?.slice(0, 10) ?? ''); const [feedback, setFeedback] = useState(''); const [busy, setBusy] = useState(false)
  const submit = async (event) => { event.preventDefault(); setFeedback(''); const numericCapacity = Number(capacity); if (!Number.isInteger(numericCapacity) || numericCapacity < 1 || numericCapacity > 10000) return setFeedback('Il limite device deve essere compreso tra 1 e 10000.'); if (license.kind === 'trial' && !endsAt) return setFeedback('La licenza trial richiede una scadenza.'); if (!confirm(`Confermi le modifiche alla licenza di ${organization.name}?`)) return; setBusy(true); try { await adminRequest(session.access_token, 'mutate', {}, { method: 'PATCH', body: JSON.stringify({ action: 'UPDATE_LICENSE', organizationId: organization.id, licenseId: license.id, status, capacity: numericCapacity, endsAt: endsAt ? new Date(`${endsAt}T23:59:59.000Z`).toISOString() : null }) }); setFeedback('Licenza aggiornata. Aggiornamento dati in corso…'); window.setTimeout(() => window.location.reload(), 500) } catch (error) { setFeedback(`Modifica non riuscita: ${error.message}`); setBusy(false) } }
  return <section className="panel license-panel"><h2>Gestione licenza</h2><form className="license-form" onSubmit={submit}><label>Stato<select value={status} onChange={(event) => setStatus(event.target.value)}>{['active','suspended','expired','revoked'].map((value) => <option key={value}>{value}</option>)}</select></label><label>Limite dispositivi<input type="number" min="1" max="10000" required value={capacity} onChange={(event) => setCapacity(event.target.value)} /></label><label>Scadenza<input type="date" required={license.kind === 'trial'} value={endsAt} onChange={(event) => setEndsAt(event.target.value)} /></label><button disabled={busy}>{busy ? 'Salvataggio…' : 'Salva licenza'}</button></form>{feedback && <p className={`notice ${feedback.startsWith('Licenza aggiornata') ? 'ok' : 'error'}`} role="status">{feedback}</p>}</section>
}

function Dashboard(){const state=useResource('dashboard');return <Page title="Stato piattaforma"><Load state={state}>{d=><><div className="cards"><Card title="Aziende attive" value={d.organizations.active} note={`${d.organizations.trial} trial · ${d.organizations.suspended} sospese`}/><Card title="Device attivi" value={d.devices.active} note={`${d.devices.revoked} revocati · ${d.devices.enrollmentPending} enrollment aperti`}/><Card title="Ispezioni oggi" value={d.inspections.today} note={`${d.inspections.last24h} nelle ultime 24h`}/><Card title="Company Cloud" value={d.health.error?'Intervento':d.health.warning?'Attenzione':'Operativo'} level={d.health.error?'error':d.health.warning?'warning':'ok'} note={`${d.health.ok} OK · ${d.health.warning} retry · ${d.health.error} anomalie`}/></div><h2>Richiede attenzione</h2>{d.attention.length?<div className="list">{d.attention.map(x=><article key={x.id}><strong>{x.name}</strong><Badge value={`${x.anomalies} anomalie`} level="error"/></article>)}</div>:<p className="empty">Nessuna anomalia rilevata.</p>}</>}</Load></Page>}
function Card({title,value,note,level}){return <article className="card"><span>{title}</span><strong className={level?`text-${level}`:''}>{value}</strong><small>{note}</small></article>}
function Organizations(){const [filters,setFilters]=useState({search:'',status:'',mode:''});const state=useResource('organizations',filters);return <Page title="Aziende"><Filters values={filters} set={setFilters} fields={['search','status','mode']}/><Load state={state}>{d=><div className="table"><div className="thead"><span>Azienda</span><span>Accesso</span><span>Device</span><span>Attività</span><span>Salute</span></div>{d.items.map(x=><NavLink key={x.id} to={`/super-admin/aziende/${x.id}`}><strong>{x.name}</strong><span>{x.license?.access_grant??'—'}</span><span>{x.devicesUsed}/{x.license?.capacity??0}</span><span>{fmt(x.lastActivityAt)}</span><Badge value={x.health==='ok'?'Regolare':'Anomalia'} level={x.health}/></NavLink>)}</div>}</Load></Page>}
function Filters({values,set,fields}){return <div className="filters">{fields.includes('search')&&<input aria-label="Cerca" placeholder="Cerca…" value={values.search} onChange={e=>set({...values,search:e.target.value})}/>} {fields.includes('status')&&<select aria-label="Stato" value={values.status} onChange={e=>set({...values,status:e.target.value})}><option value="">Tutti gli stati</option><option value="active">Attivi</option><option value="suspended">Sospesi</option><option value="revoked">Revocati</option><option value="uploading">Uploading</option><option value="available">Available</option><option value="failed">Failed</option></select>}{fields.includes('mode')&&<select aria-label="Accesso" value={values.mode} onChange={e=>set({...values,mode:e.target.value})}><option value="">Tutti gli accessi</option>{['PAID','TRIAL','TESTER','FOUNDER'].map(x=><option key={x}>{x}</option>)}</select>}</div>}
function Organization(){const {id}=useParams();const state=useResource('organization',{organizationId:id});const {session}=useSession();const [message,setMessage]=useState('');return <Page title="Dettaglio azienda"><Load state={state}>{d=><><div className="cards"><Card title="Stato" value={d.item.status}/><Card title="Device" value={d.item.devicesUsed} note={`capacità ${d.item.license?.capacity??0}`}/><Card title="Ispezioni" value={d.inspections.total} note={`${d.inspections.available} disponibili`}/><Card title="Anomalie" value={d.inspections.anomalies}/></div><section className="panel"><h2>{d.item.name}</h2><dl><dt>Organization ID</dt><dd>{d.item.id}</dd><dt>Creata</dt><dd>{fmt(d.item.created_at)}</dd><dt>Licenza</dt><dd>{d.item.license?.access_grant??'—'} · {d.item.license?.status??'—'} · scadenza {fmt(d.item.license?.ends_at)}</dd></dl><div className="actions"><button onClick={async()=>{if(!confirm(`Confermi il cambio stato per ${d.item.name}?`))return;const status=d.item.status==='active'?'suspended':'active';await adminRequest(session.access_token,'mutate',{}, {method:'PATCH',body:JSON.stringify({action:'UPDATE_ORGANIZATION',organizationId:id,status})});setMessage(`Stato aggiornato: ${status}`)}}>{d.item.status==='active'?'Sospendi':'Attiva'} organizzazione</button></div>{message&&<p className="notice ok">{message}</p>}</section></>}</Load></Page>}
function Devices(){const [filters,setFilters]=useState({status:''});const state=useResource('devices',filters);const {session}=useSession();return <Page title="Dispositivi"><Filters values={filters} set={setFilters} fields={['status']}/><Load state={state}>{d=><div className="table devices"><div className="thead"><span>Device</span><span>Azienda</span><span>Licenza</span><span>Ultima attività</span><span>Stato</span></div>{d.items.map(x=><article key={`${x.id}-${x.assignedAt}`}><strong>{x.label}</strong><span>{x.organization}</span><span>{x.license}</span><span>{fmt(x.lastActivityAt)}</span><span><Badge value={x.status}/>{x.status==='active'&&<button className="danger" onClick={async()=>{if(confirm(`Revocare ${x.label}?`))await adminRequest(session.access_token,'mutate',{}, {method:'PATCH',body:JSON.stringify({action:'REVOKE_DEVICE',deviceId:x.id})})}}>Revoca</button>}</span></article>)}</div>}</Load></Page>}
function Synchronizations(){const [filters,setFilters]=useState({status:''});const state=useResource('synchronizations',filters);return <Page title="Sincronizzazioni"><p className="sub">Il retry vive sul dispositivo: il pannello osserva lo stato reale e non simula comandi remoti.</p><Filters values={filters} set={setFilters} fields={['status']}/><Load state={state}>{d=><div className="table sync"><div className="thead"><span>Azienda / mezzo</span><span>Ispezione</span><span>Upload</span><span>Tentativi</span><span>Salute</span></div>{d.items.map(x=><article key={x.id}><strong>{x.organization}<small>{x.vehicle_plate} · {x.vehicle_description}</small></strong><span>{x.inspection_type}<small>{fmt(x.inspected_at)}</small></span><span>{x.upload_status}<small>{Math.round((x.document_size_bytes??0)/1024)} KB</small></span><span>{x.upload_attempts??0}</span><Badge value={x.health.label} level={x.health.level}/></article>)}</div>}</Load></Page>}
function Audit(){const state=useResource('audit');return <Page title="Audit"><Load state={state}>{d=><div className="table audit"><div className="thead"><span>Data</span><span>Azienda</span><span>Categoria</span><span>Risultato</span><span>Actor</span></div>{d.items.map(x=><article key={x.id}><span>{fmt(x.created_at)}</span><strong>{x.organization}</strong><span>{x.event_type}</span><span>{x.metadata?.result??'—'}</span><span>{String(x.metadata?.actorSubject??'sistema').slice(0,8)}</span></article>)}</div>}</Load></Page>}
export default function App(){return <SessionProvider><Routes><Route path="/super-admin/login" element={<Login/>}/><Route element={<MfaGuard/>}><Route path="/super-admin/mfa" element={<MfaChallengePage/>}/></Route><Route element={<Guard/>}><Route element={<Shell/>}><Route path="/super-admin/dashboard" element={<Dashboard/>}/><Route path="/super-admin/aziende" element={<Organizations/>}/><Route path="/super-admin/aziende/:id" element={<Organization/>}/><Route path="/super-admin/dispositivi" element={<Devices/>}/><Route path="/super-admin/sincronizzazioni" element={<Synchronizations/>}/><Route path="/super-admin/audit" element={<Audit/>}/><Route path="/super-admin/sicurezza" element={<MfaSecurityPage/>}/></Route></Route><Route path="*" element={<Navigate to="/super-admin/dashboard" replace/>}/></Routes></SessionProvider>}
