import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import '@fontsource-variable/manrope'
import App from './App.jsx'
import './styles.css'
import './license.css'
import './mfa.css'
import './oauth.css'
import './mfaChallenge.css'
createRoot(document.getElementById('root')).render(<StrictMode><BrowserRouter><App/></BrowserRouter></StrictMode>)
