import { randomUUID } from 'node:crypto'
import { clientsFromEnvironment,sendError,sendJson } from './companyLicensing.js'
import { authenticateDeviceRequest,resolveDeviceContext } from './deviceAuthentication.js'
import { damageInput,damagePhotoInput,publicDamage,uuid } from './companyVehicles.js'

const BUCKET='checkvan-vehicle-damages'
const extensionFor={ 'image/jpeg':'jpg','image/png':'png','image/webp':'webp' }
async function signedUpload(clients,row,recovered){const{data,error}=await clients.checkvan.storage.from(row.photo_bucket).createSignedUploadUrl(row.photo_object_path,{upsert:false});if(error)throw new Error('UPLOAD_AUTHORIZATION_FAILED');return{damage:publicDamage(row),bucket:row.photo_bucket,objectPath:row.photo_object_path,signedUploadUrl:data.signedUrl,uploadToken:data.token,recovered}}

export async function handleDeviceVehicleDamages(request,response,dependencies={}){
 if(request.method!=='POST')return sendJson(response,405,{error:'METHOD_NOT_ALLOWED'})
 try{const clients=dependencies.clients??clientsFromEnvironment(),authenticate=dependencies.authenticate??authenticateDeviceRequest,resolveContext=dependencies.resolveContext??resolveDeviceContext,device=await authenticate(request,clients),context=await resolveContext(device,clients),body=request.body??{}
  if(body.action==='LIST'){if(!uuid(body.vehicle_id))return sendJson(response,400,{error:'INVALID_VEHICLE_ID'});const{data,error}=await clients.checkvan.from('checkvan_vehicle_damages').select('*').eq('organization_id',context.organization.id).eq('vehicle_id',body.vehicle_id);if(error)throw new Error('DAMAGES_UNAVAILABLE');const visible=(data??[]).filter(row=>row.status==='CONFIRMED'||(row.status==='PENDING'&&row.reported_by_device_id===device.id&&row.photo_upload_status!=='UPLOADING'));return sendJson(response,200,{items:visible.map(publicDamage)})}
  if(body.action==='CREATE'){if(!uuid(body.vehicle_id))return sendJson(response,400,{error:'INVALID_VEHICLE_ID'});const d=damageInput(body),photo=damagePhotoInput(body),{data:existing,error:findError}=await clients.checkvan.from('checkvan_vehicle_damages').select('*').eq('reported_by_device_id',device.id).eq('client_generated_id',photo.client_generated_id).maybeSingle();if(findError)throw new Error('DAMAGES_UNAVAILABLE');if(existing){if(existing.organization_id!==context.organization.id||existing.vehicle_id!==body.vehicle_id||existing.photo_hash!==photo.photo_hash||Number(existing.photo_size_bytes)!==photo.photo_size_bytes)throw Object.assign(new Error('DAMAGE_CONFLICT'),{status:409});return sendJson(response,200,await signedUpload(clients,existing,true))}
   const id=(dependencies.randomUUID??randomUUID)(),path=`organizations/${context.organization.id}/vehicles/${body.vehicle_id}/damages/${id}/original.${extensionFor[photo.photo_mime_type]}`,row={id,organization_id:context.organization.id,vehicle_id:body.vehicle_id,damage_type:d.damage_type,vehicle_view:d.vehicle_view,normalized_x:d.x,normalized_y:d.y,status:'PENDING',reported_by_device_id:device.id,source_inspection_id:uuid(body.source_inspection_id)?body.source_inspection_id:null,...photo,photo_bucket:BUCKET,photo_object_path:path,photo_upload_status:'UPLOADING'},{data:created,error}=await clients.checkvan.from('checkvan_vehicle_damages').insert(row).select('*').single();if(error){const{data:raced}=await clients.checkvan.from('checkvan_vehicle_damages').select('*').eq('reported_by_device_id',device.id).eq('client_generated_id',photo.client_generated_id).maybeSingle();if(!raced)throw error;return sendJson(response,200,await signedUpload(clients,raced,true))}return sendJson(response,201,await signedUpload(clients,created,false))}
  if(body.action==='FINALIZE'){if(!uuid(body.damage_id))return sendJson(response,400,{error:'INVALID_DAMAGE_ID'});const{data:damage,error}=await clients.checkvan.from('checkvan_vehicle_damages').select('*').eq('id',body.damage_id).eq('organization_id',context.organization.id).eq('reported_by_device_id',device.id).maybeSingle();if(error)throw new Error('DAMAGES_UNAVAILABLE');if(!damage)throw Object.assign(new Error('DAMAGE_NOT_FOUND'),{status:404});if(damage.photo_upload_status==='AVAILABLE')return sendJson(response,200,publicDamage(damage));const parts=damage.photo_object_path.split('/'),file=parts.pop(),folder=parts.join('/'),{data:objects,error:storageError}=await clients.checkvan.storage.from(damage.photo_bucket).list(folder,{search:file,limit:2}),object=objects?.find(item=>item.name===file);if(storageError||!object)throw Object.assign(new Error('UPLOAD_NOT_FOUND'),{status:409});if(Number(object.metadata?.size)!==Number(damage.photo_size_bytes))throw Object.assign(new Error('UPLOAD_SIZE_MISMATCH'),{status:409});const{data,error:finalizeError}=await clients.checkvan.rpc('internal_device_finalize_checkvan_damage',{p_device_id:device.id,p_organization_id:context.organization.id,p_damage_id:damage.id});if(finalizeError)throw Object.assign(new Error(finalizeError.message),{status:400});return sendJson(response,200,publicDamage(data))}
  if(body.action==='PHOTO_REPLACE_CREATE'){if(!uuid(body.damage_id))return sendJson(response,400,{error:'INVALID_DAMAGE_ID'});const photo=damagePhotoInput(body),{data:damage,error}=await clients.checkvan.from('checkvan_vehicle_damages').select('*').eq('id',body.damage_id).eq('organization_id',context.organization.id).eq('reported_by_device_id',device.id).maybeSingle();if(error)throw new Error('DAMAGES_UNAVAILABLE');if(!damage)throw Object.assign(new Error('DAMAGE_NOT_FOUND'),{status:404});if(damage.status!=='PENDING')throw Object.assign(new Error('DAMAGE_NOT_EDITABLE'),{status:400});const path=`organizations/${context.organization.id}/vehicles/${damage.vehicle_id}/damages/${damage.id}/replacements/${photo.client_generated_id}.${extensionFor[photo.photo_mime_type]}`,row={photo_bucket:BUCKET,photo_object_path:path};return sendJson(response,200,await signedUpload(clients,{...damage,...row},true))}
  if(body.action==='PHOTO_REPLACE_FINALIZE'){if(!uuid(body.damage_id))return sendJson(response,400,{error:'INVALID_DAMAGE_ID'});const photo=damagePhotoInput(body),{data:damage,error}=await clients.checkvan.from('checkvan_vehicle_damages').select('*').eq('id',body.damage_id).eq('organization_id',context.organization.id).eq('reported_by_device_id',device.id).maybeSingle();if(error)throw new Error('DAMAGES_UNAVAILABLE');if(!damage)throw Object.assign(new Error('DAMAGE_NOT_FOUND'),{status:404});if(damage.status!=='PENDING')throw Object.assign(new Error('DAMAGE_NOT_EDITABLE'),{status:400});const path=`organizations/${context.organization.id}/vehicles/${damage.vehicle_id}/damages/${damage.id}/replacements/${photo.client_generated_id}.${extensionFor[photo.photo_mime_type]}`;if(damage.photo_object_path===path)return sendJson(response,200,publicDamage(damage));const parts=path.split('/'),file=parts.pop(),folder=parts.join('/'),{data:objects,error:storageError}=await clients.checkvan.storage.from(BUCKET).list(folder,{search:file,limit:2}),object=objects?.find(item=>item.name===file);if(storageError||!object)throw Object.assign(new Error('UPLOAD_NOT_FOUND'),{status:409});if(Number(object.metadata?.size)!==photo.photo_size_bytes)throw Object.assign(new Error('UPLOAD_SIZE_MISMATCH'),{status:409});const oldBucket=damage.photo_bucket,oldPath=damage.photo_object_path,{data,error:rpcError}=await clients.checkvan.rpc('internal_device_set_pending_damage_photo',{p_device_id:device.id,p_organization_id:context.organization.id,p_damage_id:damage.id,p_bucket:BUCKET,p_object_path:path,p_hash:photo.photo_hash,p_size_bytes:photo.photo_size_bytes,p_mime_type:photo.photo_mime_type});if(rpcError)throw Object.assign(new Error(rpcError.message),{status:400});if(oldBucket&&oldPath&&oldPath!==path)void clients.checkvan.storage.from(oldBucket).remove([oldPath]);return sendJson(response,200,publicDamage(data))}
  if(body.action==='PHOTO_REMOVE'){if(!uuid(body.damage_id))return sendJson(response,400,{error:'INVALID_DAMAGE_ID'});const{data:damage,error}=await clients.checkvan.from('checkvan_vehicle_damages').select('*').eq('id',body.damage_id).eq('organization_id',context.organization.id).eq('reported_by_device_id',device.id).maybeSingle();if(error)throw new Error('DAMAGES_UNAVAILABLE');if(!damage)throw Object.assign(new Error('DAMAGE_NOT_FOUND'),{status:404});if(damage.status!=='PENDING')throw Object.assign(new Error('DAMAGE_NOT_EDITABLE'),{status:400});const{data,error:rpcError}=await clients.checkvan.rpc('internal_device_remove_pending_damage_photo',{p_device_id:device.id,p_organization_id:context.organization.id,p_damage_id:damage.id});if(rpcError)throw Object.assign(new Error(rpcError.message),{status:400});if(damage.photo_bucket&&damage.photo_object_path)void clients.checkvan.storage.from(damage.photo_bucket).remove([damage.photo_object_path]);return sendJson(response,200,publicDamage(data))}
  if(body.action==='UPDATE'||body.action==='DELETE'){if(!uuid(body.damage_id))return sendJson(response,400,{error:'INVALID_DAMAGE_ID'});const d=body.action==='DELETE'?{damage_type:'SCRATCH',vehicle_view:'FRONT',x:0,y:0}:damageInput(body),{data,error}=await clients.checkvan.rpc('internal_device_update_pending_checkvan_damage',{p_device_id:device.id,p_organization_id:context.organization.id,p_damage_id:body.damage_id,p_damage_type:d.damage_type,p_vehicle_view:d.vehicle_view,p_x:d.x,p_y:d.y,p_withdraw:body.action==='DELETE'});if(error)throw Object.assign(new Error(error.message),{status:400});return sendJson(response,200,publicDamage(data))}
  return sendJson(response,400,{error:'INVALID_ACTION'})
 }catch(error){return sendError(response,error)}
}
