import { useReducer, useRef } from 'react'
import MetaDescription from '../components/common/MetaDescription.jsx'
import {
  checkvanVerificationReducer,
  initialCheckvanVerificationState,
  MAX_CHECKVAN_BATCH_FILES,
  MAX_CHECKVAN_PDF_BYTES,
  summarizeCheckvanResults,
  validateCheckvanBatch,
  verifyCheckvanFiles,
} from '../lib/checkvanFileVerification.js'
import {
  isCheckvanSupabaseConfigured,
  verifyCheckvanDocumentHash,
} from '../lib/checkvanSupabase.js'
import { useI18n } from '../i18n/useI18n.js'

const MAX_SIZE_MIB = MAX_CHECKVAN_PDF_BYTES / 1024 / 1024

function CheckVanVerificationPage() {
  const { t } = useI18n()
  const fileInputRef = useRef(null)
  const [state, dispatch] = useReducer(
    checkvanVerificationReducer,
    initialCheckvanVerificationState,
  )
  const { files, isVerifying, results, selectionError } = state
  const summary = summarizeCheckvanResults(results)
  const isBatch = files.length > 1

  const getValidationMessage = (error) => {
    if (error.code === 'batch_size') {
      return t(
        `Puoi verificare fino a ${MAX_CHECKVAN_BATCH_FILES} documenti alla volta.`,
        `You can verify up to ${MAX_CHECKVAN_BATCH_FILES} documents at a time.`,
      )
    }

    if (error.code === 'size') {
      return t(
        `${error.file.name} supera il limite massimo di ${MAX_SIZE_MIB} MB.`,
        `${error.file.name} exceeds the ${MAX_SIZE_MIB} MB limit.`,
      )
    }

    if (error.code === 'empty') {
      return t(`${error.file.name} è vuoto.`, `${error.file.name} is empty.`)
    }

    return t(
      `${error.file.name} non è un file PDF valido.`,
      `${error.file.name} is not a valid PDF file.`,
    )
  }

  const handleFileChange = (event) => {
    const selectedFiles = Array.from(event.target.files ?? [])
    const validationError = validateCheckvanBatch(selectedFiles)

    if (validationError) {
      event.target.value = ''
      dispatch({ type: 'reject', message: getValidationMessage(validationError) })
      return
    }

    dispatch({ type: 'select', files: selectedFiles })
  }

  const handleSubmit = async (event) => {
    event.preventDefault()
    const validationError = validateCheckvanBatch(files)

    if (validationError || files.length === 0) {
      dispatch({
        type: 'reject',
        message: validationError
          ? getValidationMessage(validationError)
          : t('Seleziona almeno un file PDF valido.', 'Select at least one valid PDF file.'),
      })
      return
    }

    dispatch({ type: 'start' })
    const verificationResults = await verifyCheckvanFiles(files, verifyCheckvanDocumentHash)
    dispatch({ type: 'complete', results: verificationResults })
  }

  const resetVerification = () => {
    if (fileInputRef.current) fileInputRef.current.value = ''
    dispatch({ type: 'reset' })
    fileInputRef.current?.focus()
  }

  return (
    <>
      <MetaDescription
        title={t('Verifica PDF CheckVan | DTO Solution', 'Verify CheckVan PDF | DTO Solution')}
        content={t(
          'Verifica se un PDF CheckVan generato da Driver Utility corrisponde al documento registrato, senza caricare il file sui server DTO Solution.',
          'Check whether a CheckVan PDF generated by Driver Utility matches the registered document, without uploading the file to DTO Solution servers.',
        )}
        canonical="https://dtosolution.it/verifica-checkvan"
        openGraphUrl="https://dtosolution.it/verifica-checkvan"
      />

      <section className="page-section checkvan-verification-page">
        <div className="container checkvan-verification-layout">
          <header className="checkvan-verification-hero">
            <p className="eyebrow">CheckVan · Driver Utility</p>
            <h1>{t('Verifica documenti CheckVan', 'Verify CheckVan documents')}</h1>
            <p>{t(
              'Controlla fino a 10 PDF generati da Driver Utility e verifica se corrispondono ai documenti registrati.',
              'Check up to 10 PDFs generated by Driver Utility and verify whether they match the registered documents.',
            )}</p>
          </header>

          <aside className="checkvan-privacy-note" aria-label={t('Informazioni sulla privacy', 'Privacy information')}>
            <span className="checkvan-privacy-note__icon" aria-hidden="true">✓</span>
            <div>
              <strong>{t('I PDF rimangono sul tuo dispositivo', 'The PDFs remain on your device')}</strong>
              <p>{t(
                'Nessun file viene caricato: SHA-256 viene calcolato nel browser e solo il codice risultante viene verificato.',
                'No file is uploaded: SHA-256 is calculated in the browser and only the resulting code is checked.',
              )}</p>
            </div>
          </aside>

          <form className="checkvan-verification-form" onSubmit={handleSubmit}>
            <div className="checkvan-file-field">
              <div>
                <label htmlFor="checkvan-pdf">{t('Seleziona i PDF CheckVan', 'Select the CheckVan PDFs')}</label>
                <small>{t(
                  `Da 1 a ${MAX_CHECKVAN_BATCH_FILES} PDF, massimo ${MAX_SIZE_MIB} MB per file.`,
                  `From 1 to ${MAX_CHECKVAN_BATCH_FILES} PDFs, maximum ${MAX_SIZE_MIB} MB per file.`,
                )}</small>
              </div>
              <input
                id="checkvan-pdf"
                ref={fileInputRef}
                type="file"
                accept="application/pdf,.pdf"
                multiple
                onChange={handleFileChange}
                disabled={isVerifying || results.length > 0}
              />
            </div>

            {files.length > 0 ? (
              <div className="checkvan-selected-files">
                <p>
                  <strong>{t(
                    files.length === 1 ? '1 documento selezionato' : `${files.length} documenti selezionati`,
                    files.length === 1 ? '1 document selected' : `${files.length} documents selected`,
                  )}</strong>
                </p>
                <ul>
                  {files.map((file, index) => <li key={`${file.name}-${file.size}-${index}`}>{file.name}</li>)}
                </ul>
              </div>
            ) : null}

            <div className="checkvan-form-actions">
              <button
                className="button button--primary"
                type="submit"
                disabled={!files.length || isVerifying || results.length > 0 || !isCheckvanSupabaseConfigured}
              >
                {isVerifying
                  ? t('Verifica in corso…', 'Verification in progress…')
                  : t(
                      files.length > 1 ? 'Verifica documenti' : 'Verifica documento',
                      files.length > 1 ? 'Verify documents' : 'Verify document',
                    )}
              </button>
            </div>

            {!isCheckvanSupabaseConfigured ? (
              <p className="checkvan-local-error" role="alert">
                {t(
                  'Verifica temporaneamente non disponibile. Riprova tra poco.',
                  'Verification is temporarily unavailable. Please try again shortly.',
                )}
              </p>
            ) : null}
            {selectionError ? <p className="checkvan-local-error" role="alert">{selectionError}</p> : null}
            {isVerifying ? (
              <p className="checkvan-progress" role="status">
                {t(
                  `Controllo di ${files.length} ${files.length === 1 ? 'documento' : 'documenti'} in corso…`,
                  `Checking ${files.length} ${files.length === 1 ? 'document' : 'documents'}…`,
                )}
              </p>
            ) : null}
          </form>

          {results.length > 0 ? (
            <section className="checkvan-results" aria-labelledby="checkvan-results-title">
              <div className="checkvan-results__heading">
                <div>
                  <p className="eyebrow">{t('Esito del controllo', 'Verification outcome')}</p>
                  <h2 id="checkvan-results-title">{t(
                    isBatch ? 'Risultati dei documenti' : 'Risultato del documento',
                    isBatch ? 'Document results' : 'Document result',
                  )}</h2>
                </div>
                <dl className="checkvan-summary" aria-label={t('Riepilogo', 'Summary')}>
                  <div><dt>{t('Controllati', 'Checked')}</dt><dd>{results.length}</dd></div>
                  <div><dt>{t('Verificati', 'Verified')}</dt><dd>{summary.verified}</dd></div>
                  <div><dt>{t('Non verificati', 'Not verified')}</dt><dd>{summary.not_verified}</dd></div>
                  {summary.unavailable > 0 ? (
                    <div><dt>{t('Non completati', 'Not completed')}</dt><dd>{summary.unavailable}</dd></div>
                  ) : null}
                </dl>
              </div>

              <div className="checkvan-result-list" aria-live="polite">
                {results.map((result, index) => (
                  <article
                    className={`checkvan-result checkvan-result--${result.status.replace('_', '-')}`}
                    key={`${result.name}-${index}`}
                    role={result.status === 'unavailable' ? 'alert' : 'status'}
                  >
                    <span className="checkvan-result__mark" aria-hidden="true">
                      {result.status === 'verified' ? '✓' : result.status === 'not_verified' ? '×' : '!'}
                    </span>
                    <div>
                      <p className="checkvan-result__file">{result.name}</p>
                      <h3>{result.status === 'verified'
                        ? t('Documento verificato', 'Document verified')
                        : result.status === 'not_verified'
                          ? t('Documento non verificato', 'Document not verified')
                          : t('Verifica temporaneamente non disponibile', 'Verification temporarily unavailable')}
                      </h3>
                      <p>{result.status === 'verified'
                        ? t(
                            'Corrisponde esattamente a un documento registrato da Driver Utility.',
                            'It exactly matches a document registered by Driver Utility.',
                          )
                        : result.status === 'not_verified'
                          ? t(
                              'Potrebbe essere stato modificato, non provenire da Driver Utility o non essere presente nel registro.',
                              'It may have been modified, may not come from Driver Utility, or may not be present in the registry.',
                            )
                          : t(
                              'Non è stato possibile completare questo controllo. Riprova tra poco.',
                              'This check could not be completed. Please try again shortly.',
                            )}
                      </p>
                    </div>
                  </article>
                ))}
              </div>

              <button className="button button--secondary" type="button" onClick={resetVerification}>
                {t(
                  isBatch ? 'Verifica altri documenti' : 'Verifica un altro documento',
                  isBatch ? 'Verify other documents' : 'Verify another document',
                )}
              </button>
            </section>
          ) : null}
        </div>
      </section>
    </>
  )
}

export default CheckVanVerificationPage
