import { useState } from 'react'
import MetaDescription from '../components/common/MetaDescription.jsx'
import {
  calculateSha256,
  MAX_CHECKVAN_PDF_BYTES,
  validateCheckvanPdf,
} from '../lib/checkvanFileVerification.js'
import {
  isCheckvanSupabaseConfigured,
  verifyCheckvanDocumentHash,
} from '../lib/checkvanSupabase.js'
import { useI18n } from '../i18n/useI18n.js'

const MAX_SIZE_MIB = MAX_CHECKVAN_PDF_BYTES / 1024 / 1024

function CheckVanVerificationPage() {
  const { t } = useI18n()
  const [file, setFile] = useState(null)
  const [localError, setLocalError] = useState('')
  const [result, setResult] = useState(null)
  const [isVerifying, setIsVerifying] = useState(false)

  const resetResult = () => {
    setLocalError('')
    setResult(null)
  }

  const handleFileChange = (event) => {
    const selectedFile = event.target.files?.[0] ?? null
    resetResult()

    const validationError = validateCheckvanPdf(selectedFile)
    if (validationError) {
      setFile(null)
      event.target.value = ''
      if (validationError === 'size') {
        setLocalError(t(
          `Il PDF supera il limite massimo di ${MAX_SIZE_MIB} MB. Seleziona un file più piccolo.`,
          `The PDF exceeds the ${MAX_SIZE_MIB} MB limit. Select a smaller file.`,
        ))
      } else if (validationError === 'empty') {
        setLocalError(t('Il PDF selezionato è vuoto.', 'The selected PDF is empty.'))
      } else if (validationError !== 'missing') {
        setLocalError(t('Seleziona un file PDF valido.', 'Select a valid PDF file.'))
      }
      return
    }

    setFile(selectedFile)
  }

  const handleSubmit = async (event) => {
    event.preventDefault()
    resetResult()

    const validationError = validateCheckvanPdf(file)
    if (validationError) {
      setLocalError(t('Seleziona un file PDF valido.', 'Select a valid PDF file.'))
      return
    }

    setIsVerifying(true)

    try {
      const sha256 = await calculateSha256(file)
      const isVerified = await verifyCheckvanDocumentHash(sha256)
      setResult(isVerified ? 'verified' : 'not_verified')
    } catch {
      setResult('unavailable')
    } finally {
      setIsVerifying(false)
    }
  }

  return (
    <>
      <MetaDescription
        title={t('Verifica PDF CheckVan | DTO Solution', 'Verify CheckVan PDF | DTO Solution')}
        content={t(
          'Verifica se un PDF CheckVan generato da Driver Utility corrisponde al documento registrato, senza caricare il file sui server DTO Solution.',
          'Check whether a CheckVan PDF generated by Driver Utility matches the registered document, without uploading the file to DTO Solution servers.',
        )}
        canonical="https://dtosolution.it/verifica-checkvan"
        openGraphUrl="https://dtosolution.it/verifica-checkvan"
      />

      <section className="page-section checkvan-verification-page">
        <div className="container checkvan-verification-layout">
          <header className="page-intro">
            <p className="eyebrow">CheckVan · Driver Utility</p>
            <h1>{t('Verifica documento CheckVan', 'Verify a CheckVan document')}</h1>
            <div className="page-intro__copy">
              <p>{t(
                'Seleziona un PDF generato da Driver Utility per verificare se corrisponde al documento registrato.',
                'Select a PDF generated by Driver Utility to check whether it matches the registered document.',
              )}</p>
            </div>
          </header>

          <div className="checkvan-privacy-note">
            <strong>{t('Il PDF rimane sul tuo dispositivo.', 'The PDF remains on your device.')}</strong>
            <p>{t(
              'Il PDF non viene caricato sui nostri server. Il controllo SHA-256 viene eseguito direttamente nel tuo browser.',
              'The PDF is not uploaded to our servers. The SHA-256 check runs directly in your browser.',
            )}</p>
          </div>

          <form className="checkvan-verification-form" onSubmit={handleSubmit}>
            <div className="checkvan-file-field">
              <label htmlFor="checkvan-pdf">{t('Seleziona il PDF CheckVan', 'Select the CheckVan PDF')}</label>
              <input
                id="checkvan-pdf"
                type="file"
                accept="application/pdf,.pdf"
                onChange={handleFileChange}
                disabled={isVerifying}
              />
              <small>{t(
                `Formato PDF, massimo ${MAX_SIZE_MIB} MB.`,
                `PDF format, maximum ${MAX_SIZE_MIB} MB.`,
              )}</small>
            </div>

            {file ? (
              <p className="checkvan-selected-file">
                <span>{t('File selezionato', 'Selected file')}</span>
                <strong>{file.name}</strong>
              </p>
            ) : null}

            <button
              className="button button--primary"
              type="submit"
              disabled={!file || isVerifying || !isCheckvanSupabaseConfigured}
            >
              {isVerifying
                ? t('Verifica in corso…', 'Verification in progress…')
                : t('Verifica documento', 'Verify document')}
            </button>

            {!isCheckvanSupabaseConfigured ? (
              <p className="checkvan-local-error" role="alert">
                {t(
                  'Verifica temporaneamente non disponibile. Riprova tra poco.',
                  'Verification is temporarily unavailable. Please try again shortly.',
                )}
              </p>
            ) : null}
            {localError ? <p className="checkvan-local-error" role="alert">{localError}</p> : null}
            {isVerifying ? (
              <p className="checkvan-progress" role="status">
                {t(
                  'Calcolo SHA-256 e controllo del registro in corso…',
                  'Calculating SHA-256 and checking the registry…',
                )}
              </p>
            ) : null}
          </form>

          {result === 'verified' ? (
            <section className="checkvan-result checkvan-result--verified" role="status">
              <h2>{t('Documento verificato', 'Document verified')}</h2>
              <p>{t(
                'Questo PDF corrisponde esattamente a un documento registrato da Driver Utility.',
                'This PDF exactly matches a document registered by Driver Utility.',
              )}</p>
              <p>{t(
                'Il file selezionato non presenta differenze rispetto alla versione registrata.',
                'The selected file has no differences from the registered version.',
              )}</p>
            </section>
          ) : null}

          {result === 'not_verified' ? (
            <section className="checkvan-result checkvan-result--not-verified" role="status">
              <h2>{t('Documento non verificato', 'Document not verified')}</h2>
              <p>{t(
                'Questo PDF non corrisponde a nessun documento CheckVan registrato.',
                'This PDF does not match any registered CheckVan document.',
              )}</p>
              <p>{t(
                'Il file potrebbe essere stato modificato, potrebbe non provenire da Driver Utility oppure potrebbe non essere presente nel registro.',
                'The file may have been modified, may not come from Driver Utility, or may not be present in the registry.',
              )}</p>
            </section>
          ) : null}

          {result === 'unavailable' ? (
            <section className="checkvan-result checkvan-result--unavailable" role="alert">
              <h2>{t(
                'Verifica temporaneamente non disponibile',
                'Verification temporarily unavailable',
              )}</h2>
              <p>{t(
                'Non è stato possibile completare il controllo. Riprova tra poco.',
                'The check could not be completed. Please try again shortly.',
              )}</p>
            </section>
          ) : null}
        </div>
      </section>
    </>
  )
}

export default CheckVanVerificationPage
