import { Link } from 'react-router-dom'
import MetaDescription from '../components/common/MetaDescription.jsx'
import { driverLegislation, futureDriverTopics } from '../data/driverLegislation.js'

export default function DriverLegislationPage() {
  return <article className="page-section driver-area"><MetaDescription content="Normativa di riferimento per driver e lavoratori: sintesi su orario, sicurezza, contratti e trasparenza con fonti ufficiali." /><div className="container">
    <header className="page-intro"><Link to="/area-driver">Torna all’Area Driver</Link><p className="eyebrow">Riferimenti legislativi</p><h1>Normativa di riferimento</h1><p>Leggi e disposizioni utili per gli aspetti non disciplinati direttamente dal contratto collettivo.</p><p>Legge e contratto collettivo concorrono a regolare il rapporto: queste schede non stabiliscono quale disciplina si applichi automaticamente al tuo caso. Verifica il testo vigente e il campo di applicazione della singola norma.</p><p className="driver-area__notice">Sintesi informative, non consulenza legale o sindacale. Le sintesi non sostituiscono i testi ufficiali. Riferimenti verificati il 5 settembre 2026.</p></header>
    <nav className="driver-legislation__index" aria-label="Indice della normativa">{driverLegislation.map(law => <a href={`#${law.id}`} key={law.id}>{law.number}</a>)}</nav>
    <section className="driver-area__section" aria-labelledby="legislation-title"><h2 id="legislation-title">Normativa generale e disposizioni speciali</h2><div className="driver-area__grid">{driverLegislation.map(law => <article className="driver-area-card" id={law.id} key={law.id}><p className="eyebrow">{law.number}</p><h3>{law.title}</h3><p>{law.summary}</p><h4>Quando può esserti utile</h4><p>{law.useful}</p><ul>{law.topics.map(topic => <li key={topic}>{topic}</li>)}</ul><a className="button button--secondary" href={law.source} target="_blank" rel="noopener noreferrer">{law.sourceLabel} <span className="sr-only">(si apre in una nuova scheda)</span></a>{law.sourceNote && <p>{law.sourceNote}</p>}<small>Questa sintesi non sostituisce il testo ufficiale e le sue successive modifiche.</small></article>)}</div></section>
    <section className="driver-area__section" aria-labelledby="contract-references-title"><h2 id="contract-references-title">Documenti contrattuali separati</h2><p>Il CCNL e l’accordo specifico sono consultabili nelle rispettive pagine; non sono presentati come norme valide indistintamente per tutti i lavoratori.</p><div className="driver-backup__buttons"><Link to="/area-driver/ccnl-logistica-trasporto-merci-spedizione">CCNL Logistica, Trasporto Merci e Spedizione</Link><Link to="/area-driver/accordo-asso-espressi-ultimo-miglio-2025">Accordo Assoespressi – Ultimo miglio Amazon</Link></div></section>
    <section className="driver-area__section" aria-labelledby="future-topics-title"><h2 id="future-topics-title">Prossimi approfondimenti</h2><p>Sezioni da sviluppare dopo la verifica delle relative fonti ufficiali.</p><ul>{futureDriverTopics.map(topic => <li key={topic}>{topic} — in preparazione</li>)}</ul></section>
  </div></article>
}
