import { useCallback, useEffect, useState } from 'react'
import { Navigate } from 'react-router-dom'
import { useAuth } from '../auth/AuthContext.jsx'
import { canManageVehicles } from '../access.js'
import { copyPreviousAssignments, loadCompanyAssignments, saveCompanyAssignment } from '../lib/companySupabase.js'
import { COMPANY_ROUTES } from '../routes.js'
const today = () => new Date().toLocaleDateString('en-CA')
export default function AssignmentsPage() {
  const { access, session } = useAuth()
  const [date, setDate] = useState(today), [data, setData] = useState({ drivers: [], vehicles: [], assignments: [] }), [error, setError] = useState(''), [saving, setSaving] = useState(''), [saved, setSaved] = useState(''), [copying, setCopying] = useState(false)
  const refresh = useCallback(() => loadCompanyAssignments(session.access_token, date).then(setData).catch(() => setError('Assegnazioni non disponibili.')), [date, session.access_token])
  useEffect(() => { if (canManageVehicles(access)) void refresh() }, [access, refresh])
  if (!canManageVehicles(access)) return <Navigate to={COMPANY_ROUTES.dashboard} replace />
  const assign = async (driver_id, vehicle_id) => { if (!vehicle_id || saving) return; setSaving(driver_id); setSaved(''); setError(''); try { await saveCompanyAssignment(session.access_token, { assignment_date: date, driver_id, vehicle_id }); await refresh(); setSaved(driver_id); window.setTimeout(() => setSaved((value) => value === driver_id ? '' : value), 1600) } catch { setError('Il mezzo o il driver risulta già assegnato per questa data.') } finally { setSaving('') } }
  const copyPrevious = async () => { if (copying) return; setCopying(true); setError(''); try { await copyPreviousAssignments(session.access_token, date); await refresh() } catch { setError('Copia delle assegnazioni non riuscita.') } finally { setCopying(false) } }
  return <div className="company-page assignments-page"><header><p className="company-kicker">Pianificazione</p><h1>Assegnazioni giornaliere</h1><p>Un mezzo per driver e un driver per mezzo, con storico per data.</p></header>{error && <p className="notice notice--error">{error}</p>}<div className="assignments-toolbar"><label>Data<input aria-label="Data assegnazioni" type="date" value={date} onChange={(e) => setDate(e.target.value)}/></label><button className="button-secondary" disabled={copying} onClick={() => void copyPrevious()}>{copying ? 'Copia in corso…' : 'Copia ultimo giorno disponibile'}</button></div><div className="assignments-head" aria-hidden="true"><span>Driver</span><span>Mezzo assegnato oggi</span></div><section className="assignments-list">{data.drivers.map((driver) => { const current = data.assignments.find((item) => item.driver_id === driver.driver_id); return <article className="assignment-row" key={driver.driver_id}><div className="assignment-driver"><strong>{driver.last_name} {driver.first_name}</strong><small>{driver.driver_code || 'Senza codice'}</small></div><div className="assignment-control"><select aria-label={`Mezzo di ${driver.first_name} ${driver.last_name}`} value={current?.vehicle_id || ''} disabled={saving === driver.driver_id} onChange={(e) => void assign(driver.driver_id, e.target.value)}><option value="">Non assegnato</option>{data.vehicles.map((vehicle) => <option key={vehicle.vehicle_id} value={vehicle.vehicle_id} disabled={data.assignments.some((item) => item.vehicle_id === vehicle.vehicle_id && item.driver_id !== driver.driver_id)}>{vehicle.internal_code} · {vehicle.plate}</option>)}</select><small className="assignment-feedback" aria-live="polite">{saving === driver.driver_id ? 'Salvataggio…' : saved === driver.driver_id ? 'Salvato' : ''}</small></div></article> })}</section></div>
}
