import { useCallback, useEffect, useRef, useState } from 'react'
import { Navigate } from 'react-router-dom'
import { useAuth } from '../auth/AuthContext.jsx'
import { canManageVehicles } from '../access.js'
import { createCompanyDriver, importCompanyDrivers, loadCompanyDrivers, updateCompanyDriver } from '../lib/companySupabase.js'
import { importableDriverRows, parseDriverCsv } from '../lib/driverCsv.js'
import { COMPANY_ROUTES } from '../routes.js'

const empty = { driver_code: '', first_name: '', last_name: '' }
export default function DriversPage() {
  const { access, session } = useAuth()
  const [items, setItems] = useState([]), [form, setForm] = useState(empty), [error, setError] = useState(''), [preview, setPreview] = useState(null), [busy, setBusy] = useState(false)
  const fileRef = useRef(null)
  const refresh = useCallback(() => loadCompanyDrivers(session.access_token).then((value) => setItems(value.items)).catch(() => setError('Anagrafica driver non disponibile.')), [session.access_token])
  useEffect(() => { if (canManageVehicles(access)) void refresh() }, [access, refresh])
  if (!canManageVehicles(access)) return <Navigate to={COMPANY_ROUTES.dashboard} replace />
  const submit = async (event) => { event.preventDefault(); if (busy) return; setBusy(true); setError(''); try { await createCompanyDriver(session.access_token, form); setForm(empty); await refresh() } catch (reason) { setError(reason.message === 'DRIVER_CODE_EXISTS' ? 'Codice driver già presente.' : 'Creazione non riuscita.') } finally { setBusy(false) } }
  const chooseCsv = async (event) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; try { setPreview(parseDriverCsv(await file.text(), items)); setError('') } catch { setError('CSV non valido. Usa: driver_code,nome,cognome') } }
  const confirmImport = async () => { if (busy) return; setBusy(true); try { await importCompanyDrivers(session.access_token, importableDriverRows(preview)); setPreview(null); await refresh() } catch { setError('Importazione driver non riuscita.') } finally { setBusy(false) } }
  const archive = async (driver) => { if (!window.confirm(`Archiviare ${driver.first_name} ${driver.last_name}? Lo storico resterà disponibile.`)) return; await updateCompanyDriver(session.access_token, { driver_id: driver.driver_id, action: 'ARCHIVE' }); await refresh() }
  return <div className="company-page driver-directory"><header><p className="company-kicker">Organizzazione</p><h1>Driver</h1><p>Anagrafica autisti per assegnazioni e ispezioni.</p></header>{error && <p className="notice notice--error">{error}</p>}<form className="vehicle-form" onSubmit={submit}><input aria-label="Codice driver" placeholder="Codice driver (opzionale)" value={form.driver_code} onChange={(e) => setForm({ ...form, driver_code: e.target.value })}/><input aria-label="Nome" placeholder="Nome" required value={form.first_name} onChange={(e) => setForm({ ...form, first_name: e.target.value })}/><input aria-label="Cognome" placeholder="Cognome" required value={form.last_name} onChange={(e) => setForm({ ...form, last_name: e.target.value })}/><div className="vehicle-form__actions"><button disabled={busy}>Aggiungi driver</button><button type="button" className="button-secondary" onClick={() => fileRef.current?.click()}>Importa CSV</button></div><input ref={fileRef} className="visually-hidden" type="file" accept=".csv,text/csv" onChange={chooseCsv}/></form>{preview && <section className="fleet-preview"><h2>Anteprima CSV</h2><p>{preview.total} righe · {preview.ready} pronte · {preview.invalid} non valide/duplicate</p><div className="driver-preview-list">{preview.rows.map((row) => <div key={row.row}><span>{row.row}</span><strong>{row.first_name} {row.last_name}</strong><small>{row.driver_code || 'Senza codice'}</small><em>{row.valid ? 'Pronto' : row.errors.join(', ')}</em></div>)}</div><button disabled={!preview.ready || busy} onClick={() => void confirmImport()}>Importa {preview.ready} driver</button></section>}<section className="driver-list" aria-label="Elenco driver">{items.map((driver) => <article className="driver-row" key={driver.driver_id}><div className="driver-row__identity"><strong>{driver.last_name} {driver.first_name}</strong><small>{driver.driver_code || 'Senza codice'}</small></div><span className={`driver-status driver-status--${driver.status}`}>{driver.status === 'active' ? 'Attivo' : 'Archiviato'}</span>{driver.status === 'active' && <button type="button" onClick={() => void archive(driver)}>Archivia</button>}</article>)}</section></div>
}
