import { useCallback, useEffect, useRef, useState } from 'react'
import { Link, Navigate } from 'react-router-dom'
import { useAuth } from '../auth/AuthContext.jsx'
import { canManageVehicles } from '../access.js'
import { createCompanyVehicle, importCompanyVehicles, loadCompanyVehicles, loadVehicleRemovalPlan, removeCompanyVehicle } from '../lib/companySupabase.js'
import { importableFleetRows, parseFleetCsv } from '../lib/fleetCsv.js'
import { removeVehicleOptimistically } from '../lib/fleetRemovalState.js'
import { COMPANY_ROUTES } from '../routes.js'
import { groupCompanyVehicles } from '../lib/vehicleSort.js'

const empty = { internal_code: '', plate: '', silhouette_category: 'SMALL' }
export default function VehiclesPage() {
  const { access, session } = useAuth()
  const [items, setItems] = useState([]), [existing, setExisting] = useState([]), [form, setForm] = useState(empty), [error, setError] = useState('')
  const [preview, setPreview] = useState(null), [importing, setImporting] = useState(false), [removing, setRemoving] = useState(''), [report, setReport] = useState(null)
  const fileRef = useRef(null)
  const refresh = useCallback(() => loadCompanyVehicles(session.access_token).then((result) => { setItems(result.items); setExisting(result.existing ?? result.items) }).catch(() => setError('Catalogo veicoli non disponibile.')), [session.access_token])
  useEffect(() => { if (canManageVehicles(access)) void refresh() }, [access, refresh])
  if (!canManageVehicles(access)) return <Navigate to={COMPANY_ROUTES.dashboard} replace />
  const submit = async (event) => { event.preventDefault(); setError(''); try { await createCompanyVehicle(session.access_token, form); setForm(empty); await refresh() } catch (reason) { setError(reason.message === 'VEHICLE_PLATE_EXISTS' ? 'Targa già presente nell’organizzazione.' : 'Creazione non riuscita.') } }
  const chooseCsv = async (event) => { const file = event.target.files?.[0]; event.target.value = ''; setReport(null); setError(''); if (!file) return; try { setPreview(parseFleetCsv(await file.text(), existing)) } catch (reason) { setPreview(null); setError(reason.message === 'CSV_HEADER_NON_VALIDO' ? 'Header CSV non valido. Usa: codice_mezzo,targa,categoria' : 'File CSV non valido.') } }
  const confirmImport = async () => { const vehicles = importableFleetRows(preview); if (!vehicles.length || importing) return; setImporting(true); setError(''); try { const result = await importCompanyVehicles(session.access_token, vehicles); setReport({ imported: result.imported, skipped: preview.invalid + result.skipped }); setPreview(null); await refresh() } catch { setError('Importazione flotta non riuscita.') } finally { setImporting(false) } }
  const remove = async (vehicle) => { if (removing) return; setRemoving(vehicle.vehicle_id); setError(''); try { const plan = await loadVehicleRemovalPlan(session.access_token, vehicle.vehicle_id); const message = plan.hasHistory ? 'Questo veicolo ha uno storico. Verrà archiviato e non sarà più disponibile nella flotta operativa.' : 'Rimuovere definitivamente questo veicolo?'; if (!window.confirm(message)) return; await removeVehicleOptimistically({ vehicle, items, setItems, setError, request: () => removeCompanyVehicle(session.access_token, vehicle.vehicle_id) }) } catch { /* safe UI error */ } finally { setRemoving('') } }
  return <div className="company-page">
    <header><p className="company-kicker">Parco mezzi</p><h1>Veicoli</h1><p>Anagrafica e mappe danni della tua organizzazione.</p></header>
    {error && <p className="notice notice--error">{error}</p>}{report && <p className="notice">{report.imported} veicoli importati · {report.skipped} non importati</p>}
    <form className="vehicle-form" onSubmit={submit}><input aria-label="Codice mezzo" placeholder="Codice mezzo, es. S70" value={form.internal_code} onChange={(event) => setForm({ ...form, internal_code: event.target.value })} /><input aria-label="Targa" placeholder="Targa" value={form.plate} onChange={(event) => setForm({ ...form, plate: event.target.value })} /><select aria-label="Sagoma" value={form.silhouette_category} onChange={(event) => setForm({ ...form, silhouette_category: event.target.value })}><option>EXTRA_SMALL</option><option>SMALL</option><option>MEDIUM</option><option>LARGE</option></select><div className="vehicle-form__actions"><button>Aggiungi veicolo</button><button type="button" className="button-secondary" onClick={() => fileRef.current?.click()}>Importa flotta CSV</button></div><input ref={fileRef} className="visually-hidden" type="file" accept=".csv,text/csv" onChange={chooseCsv} /></form>
    {preview && <section className="fleet-preview" aria-label="Anteprima importazione flotta"><header><h2>Anteprima CSV</h2><p>{preview.total} righe lette · {preview.ready} pronte per import · {preview.invalid} con errori o duplicate</p></header><div className="fleet-preview__table"><div className="fleet-preview__head"><span>Riga</span><span>Codice mezzo</span><span>Targa</span><span>Categoria</span><span>Stato</span></div>{preview.rows.map((row) => <div key={row.row}><span>{row.row}</span><span>{row.internal_code || '—'}</span><span>{row.plate || '—'}</span><span>{row.silhouette_category || '—'}</span><span className={row.valid ? 'fleet-valid' : 'fleet-invalid'}>{row.valid ? 'Pronto' : row.errors.join(' · ')}</span></div>)}</div><footer><button type="button" className="button-secondary" onClick={() => setPreview(null)}>Annulla</button><button type="button" disabled={!preview.ready || importing} onClick={confirmImport}>{importing ? 'Importazione…' : `Importa ${preview.ready} veicoli`}</button></footer></section>}
    <section className="vehicle-categories" aria-label="Veicoli per categoria">{groupCompanyVehicles(items).map(({ category, items: categoryItems }) => <section className="vehicle-category" aria-labelledby={`vehicle-category-${category}`} key={category}><h2 id={`vehicle-category-${category}`}>{category.replace('_', ' ')}</h2><div className="vehicle-list">{categoryItems.map((vehicle) => <article className="vehicle-row" data-attention={vehicle.open_report_count>0?'true':undefined} key={vehicle.vehicle_id}><Link to={COMPANY_ROUTES.vehicle(vehicle.vehicle_id)}><strong>{vehicle.internal_code}</strong><span className="vehicle-row__plate">{vehicle.plate}</span>{vehicle.open_report_count>0&&<small className="vehicle-report-count">🔴 {vehicle.open_report_count} {vehicle.open_report_count===1?'segnalazione aperta':'segnalazioni aperte'}</small>}{vehicle.status !== 'active' && <small className="vehicle-status">Disattivato</small>}</Link><button type="button" disabled={removing === vehicle.vehicle_id} onClick={() => void remove(vehicle)}>{removing === vehicle.vehicle_id ? 'Attendi…' : 'Rimuovi'}</button></article>)}{categoryItems.length === 0 && <p className="vehicle-list__empty">Nessun veicolo</p>}</div></section>)}</section>
  </div>
}
