import AndroidProductPage from '../../components/products/AndroidProductPage.jsx'
import ButtonLink from '../../components/common/ButtonLink.jsx'
import { getApplicationBySlug } from '../../data/applications.js'
import { useI18n } from '../../i18n/useI18n.js'

const product = getApplicationBySlug('driver-utility')

const description = [
  ['Driver Utility è un’app Android pensata per semplificare il lavoro quotidiano dei driver e riunire in un unico strumento attività che normalmente richiedono applicazioni, documenti e procedure separate.', 'Driver Utility is an Android app designed to simplify a driver’s daily work by bringing together in one place tasks that would normally require separate apps, documents and procedures.'],
  ['Permette di documentare le condizioni dei mezzi prima e dopo l’utilizzo, organizzare turni e documenti di lavoro, gestire QR locali, analizzare le buste paga e accedere rapidamente alle informazioni utili durante la giornata.', 'It helps document vehicle conditions before and after use, organize shifts and work documents, manage local QR codes, review payslips and quickly access useful information throughout the working day.'],
  ['Particolare attenzione è dedicata a CheckVan, il sistema di ispezione fotografica dei veicoli: le verifiche possono essere documentate attraverso fotografie guidate, dati del mezzo, firma, posizione GPS e PDF certificati, creando una documentazione più chiara e verificabile sia per il driver sia per chi gestisce i mezzi.', 'Special attention is given to CheckVan, the vehicle inspection system: inspections can be documented through guided photographs, vehicle information, signature, GPS position and certified PDF documents, creating clearer and more verifiable records for both drivers and vehicle managers.'],
  ['Driver Utility nasce dall’esperienza diretta nel lavoro su strada ed è progettata con un obiettivo semplice: ridurre operazioni ripetitive, organizzare meglio le informazioni e fornire strumenti pratici utilizzabili direttamente dallo smartphone.', 'Driver Utility was created from direct experience of working on the road, with a simple goal: reduce repetitive tasks, organize information more effectively and provide practical tools directly from a smartphone.'],
]

const features = [
  ['Controlla Mezzi – CheckVan', 'Vehicle Checks – CheckVan', 'Crea ispezioni di presa e riconsegna del veicolo con identificativo del mezzo, rotta, targa, conducente, azienda e note. Il controllo comprende fino a 14 fotografie guidate, fotografie aggiuntive, firma sullo schermo, posizione GPS e marker informativi applicati alle immagini. Le ispezioni possono essere salvate come bozze, consultate nell’archivio e trasformate in PDF compressi o ad alta qualità.', 'Create vehicle pickup and return inspections including vehicle identifier, route, licence plate, driver, company and notes. The inspection can include up to 14 guided photographs, additional photos, on-screen signature, GPS location and information markers applied to the images. Inspections can be saved as drafts, reviewed in the archive and exported as compressed or high-quality PDF documents.'],
  ['Certificazione dei PDF CheckVan', 'CheckVan PDF Certification', 'Ogni versione del PDF può essere identificata attraverso impronta digitale e certificazione crittografica. Il sistema consente successivamente di verificare attraverso il sito DTO Solution che il documento corrisponda a quello certificato e non sia stato alterato dopo la sua creazione.', 'Each PDF version can be identified through a digital fingerprint and cryptographic certification. The DTO Solution website can later verify whether the selected document matches the certified version and whether it has been changed after creation.'],
  ['Confronto delle ispezioni', 'Inspection Comparison', 'Il sito DTO Solution mette a disposizione uno strumento dedicato per affiancare le fotografie di due ispezioni dello stesso veicolo. Le immagini possono essere ingrandite e spostate anche in modo sincronizzato, facilitando il confronto visivo tra le condizioni del mezzo in momenti differenti. La valutazione rimane umana.', 'The DTO Solution website also provides a dedicated tool for displaying the photographs from two inspections of the same vehicle side by side. Images can be zoomed and moved, including synchronized zoom and pan, to make visual comparison between different inspection moments easier. The final assessment remains entirely human.'],
  ['Turni Driver', 'Driver Shifts', 'Calendario mensile per registrare giornate lavorate, riposi, ferie, permessi, malattia, infortunio e altri eventi. Include riepiloghi mensili, gestione delle festività e possibilità di esportare il riepilogo in PDF.', 'Monthly calendar for recording worked days, rest days, holidays, leave, sickness, injury and other events. Includes monthly summaries, Italian public holiday handling and PDF export.'],
  ['Busta Paga Driver', 'Driver Payslip', 'Importa una o più buste paga PDF, estrae le informazioni riconosciute e permette di conservarne uno storico. Il sistema esegue analisi e controlli di coerenza, confronta quando possibile i dati della busta paga con i turni registrati e segnala gli elementi che richiedono verifica.', 'Import one or more payslip PDF files, extract recognized information and keep a local history. The system performs consistency checks, compares payslip data with recorded shifts when possible and highlights items that may require verification.'],
  ['QR Locali e QR Cloud', 'Local QR and QR Cloud', 'Scansiona, archivia, ricerca e condivide QR utilizzati durante il lavoro. I QR possono essere organizzati per località e vettore, individuati anche in base alla posizione e, facoltativamente, salvati e recuperati tramite il servizio cloud.', 'Scan, store, search and share QR codes used during work. QR codes can be organized by location and carrier, located using GPS and optionally backed up and restored through the cloud service.'],
  ['Ricerca nei PDF di lavoro', 'Work PDF Search', 'Driver Utility può aprire PDF ricevuti sul telefono, cercare automaticamente nome, cognome o alias configurati e portare rapidamente il driver alla corrispondenza trovata nel documento.', 'Driver Utility can open PDF documents received on the phone, automatically search for the configured name, surname or alias and take the driver directly to the matching position inside the document.'],
  ['Foto Giornata', 'Daily Photos', 'Funzione rapida per acquisire e conservare temporaneamente fotografie utili durante la giornata lavorativa, mantenendole separate dalla normale galleria personale.', 'A quick tool for taking and temporarily storing useful photographs during the working day, keeping them separate from the phone’s normal personal gallery.'],
  ['Comandi vocali e strumenti rapidi', 'Voice Input and Quick Tools', 'Nei campi supportati è possibile utilizzare la voce per inserire più velocemente informazioni come mezzo, rotta, targa e note.', 'Supported fields can use voice input to enter information such as vehicle identifier, route, licence plate and notes more quickly.'],
]

const technicalInformation = [
  ['Driver Utility è un’applicazione Android sviluppata con tecnologie web moderne integrate con le funzionalità native dello smartphone.', 'Driver Utility is an Android application built with modern web technologies integrated with native smartphone features.'],
  ['L’app utilizza direttamente, quando necessario e previa autorizzazione, fotocamera, GPS, microfono, filesystem, condivisione Android e scanner QR.', 'When required and with the user’s permission, the app uses the camera, GPS, microphone, filesystem, Android sharing functions and QR scanner.'],
  ['Gran parte delle funzioni operative e dei dati viene gestita localmente sul dispositivo, permettendo di continuare a utilizzare le principali funzionalità anche in assenza di connessione. Internet viene utilizzato per specifici servizi opzionali o remoti, tra cui QR Cloud, sincronizzazione delle certificazioni CheckVan, riconoscimento online della targa, backup su Google Drive e aggiornamenti tramite Google Play.', 'A large part of the operational data and functionality is handled locally on the device, allowing the main features to remain usable even without an Internet connection. Internet access is required only for specific optional or remote services, including QR Cloud, CheckVan certification synchronization, online licence plate recognition, Google Drive backup and Google Play updates.'],
  ['I PDF CheckVan vengono generati direttamente sul dispositivo. Per la certificazione viene calcolata un’impronta SHA-256 del documento e utilizzata una firma crittografica ECDSA P-256/SHA-256, con chiave privata protetta dal sistema Android. Il registro remoto conserva i dati necessari alla certificazione, non il contenuto del PDF.', 'CheckVan PDF documents are generated directly on the device. For certification, the application calculates a SHA-256 digital fingerprint of the document and uses an ECDSA P-256/SHA-256 cryptographic signature, with the private key protected by the Android system. The remote registry stores only the information required for certification, not the PDF file itself.'],
  ['La copia dei PDF CheckVan su Google Drive è facoltativa. Le buste paga e gli altri PDF compatibili vengono analizzati localmente; eventuali risultati automatici o controlli di coerenza non sostituiscono la verifica del documento originale.', 'Google Drive backup of CheckVan PDFs is optional. Payslips and other compatible PDF documents are processed locally; automated results and consistency checks do not replace verification against the original document.'],
]

const faqItems = [
  ['Driver Utility è pensata solo per i driver Amazon?', 'Is Driver Utility designed only for Amazon drivers?', 'No. Diverse funzioni sono state sviluppate partendo da esigenze reali del lavoro di consegna, ma Driver Utility è pensata per poter essere utilizzata anche da driver e realtà operative differenti.', 'No. Several features were developed from real delivery-work needs, but Driver Utility is designed to be useful for drivers and operational environments beyond Amazon.'],
  ['Posso utilizzare Driver Utility senza connessione Internet?', 'Can I use Driver Utility without an Internet connection?', 'Sì. Molte delle principali funzioni lavorano direttamente sul dispositivo. La connessione è necessaria solamente per determinati servizi online, come cloud, backup Google Drive, alcuni riconoscimenti e sincronizzazioni.', 'Yes. Many of the main features work directly on the device. An Internet connection is required only for specific online services such as cloud features, Google Drive backup, certain recognition services and synchronization.'],
  ['Le fotografie delle ispezioni vengono inviate automaticamente a un server?', 'Are inspection photos automatically uploaded to a server?', 'No. La generazione e la gestione dell’ispezione avvengono sul dispositivo. L’eventuale copia del PDF su Google Drive dipende dalle impostazioni scelte dall’utente.', 'No. The inspection is generated and managed on the device. A copy of the PDF is uploaded to Google Drive only if the user has enabled that option.'],
  ['Che cosa significa “PDF certificato”?', 'What does “certified PDF” mean?', 'Driver Utility calcola un’impronta digitale del PDF e crea una certificazione crittografica collegata a quella specifica versione del documento. In questo modo è possibile controllare successivamente se il file sottoposto a verifica corrisponde al documento originariamente certificato.', 'Driver Utility calculates a digital fingerprint of the PDF and creates a cryptographic certification linked to that specific document version. This makes it possible to verify later whether a submitted file matches the originally certified document.'],
  ['Il sito DTO Solution conserva il PDF quando lo verifico?', 'Does the DTO Solution website store the PDF when I verify it?', 'La certificazione remota non richiede di conservare nel registro il contenuto del PDF: vengono registrati i dati crittografici e i metadati necessari alla verifica.', 'No PDF needs to be stored in the remote certification registry. Only the cryptographic information and metadata required for verification are registered.'],
  ['A cosa serve il confronto delle ispezioni CheckVan?', 'What is the CheckVan inspection comparison tool for?', 'Permette di visualizzare affiancate le fotografie di due controlli dello stesso veicolo e di ingrandirle o spostarle per facilitare l’individuazione visiva di eventuali differenze. La valutazione rimane umana: lo strumento facilita il confronto, non decide automaticamente se è presente un danno.', 'It displays the photographs from two inspections of the same vehicle side by side and allows them to be zoomed and moved to make visual differences easier to inspect. The tool does not automatically decide whether damage is present: the assessment remains human.'],
  ['Le 14 fotografie CheckVan sono obbligatorie?', 'Are all 14 CheckVan photographs mandatory?', 'Dipende dalla configurazione. Driver Utility può richiedere il completamento delle viste previste oppure consentire di proseguire dopo aver segnalato quelle mancanti.', 'It depends on the configuration. Driver Utility can require all guided views to be completed, or allow the inspection to continue after warning that some photographs are missing.'],
  ['Driver Utility può controllare la mia busta paga?', 'Can Driver Utility check my payslip?', 'Può leggere i PDF supportati, organizzare i dati, confrontarli con altre informazioni disponibili e segnalare possibili incongruenze o elementi da verificare. I risultati automatici non sostituiscono il documento originale né una verifica professionale quando necessaria.', 'It can read supported PDF files, organize the extracted information, compare it with other available data and highlight possible inconsistencies or items that may require review. Automated results do not replace the original payslip or professional advice when needed.'],
  ['Dove vengono conservati i miei dati?', 'Where is my data stored?', 'Una parte importante dei dati operativi viene conservata localmente sul dispositivo. Alcuni servizi facoltativi utilizzano invece servizi esterni, ad esempio Supabase per specifiche funzioni cloud e Google Drive quando l’utente sceglie di utilizzarlo.', 'A significant part of the operational data is stored locally on the device. Some optional services use external systems, such as Supabase for specific cloud features and Google Drive when the user chooses to use it.'],
  ['Posso condividere i PDF delle ispezioni?', 'Can I share inspection PDFs?', 'Sì. I PDF CheckVan possono essere aperti e condivisi utilizzando le normali funzioni Android e, se configurato, può esserne salvata una copia su Google Drive.', 'Yes. CheckVan PDFs can be opened and shared using the standard Android sharing functions and, if configured, a copy can also be saved to Google Drive.'],
]

function DriverUtilityPage() {
  const { t } = useI18n()
  const localizedProduct = {
    ...product,
    heroDescription: t(product.heroDescription, 'Practical tools designed to simplify a driver’s daily work, from vehicle management to day-to-day organization.'),
    heroHighlights: [t(product.heroHighlights[0], 'Designed for real work on the road'), t(product.heroHighlights[1], 'Essential tools in one app')],
    mediaEyebrow: t(product.mediaEyebrow, 'THE APP IN ACTION'),
  }

  return (
    <AndroidProductPage
      product={localizedProduct}
      description={<div className="product-prose">{description.map(([it, en]) => <p key={it}>{t(it, en)}</p>)}</div>}
      features={<div className="product-feature-list">{features.map(([itTitle, enTitle, itCopy, enCopy]) => <section key={itTitle}><h3>{t(itTitle, enTitle)}</h3><p>{t(itCopy, enCopy)}</p></section>)}</div>}
      technicalInformation={<div className="product-prose product-technical-list">{technicalInformation.map(([it, en]) => <p key={it}>{t(it, en)}</p>)}</div>}
      faqItems={faqItems.map(([itQuestion, enQuestion, itAnswer, enAnswer]) => ({ question: t(itQuestion, enQuestion), answer: t(itAnswer, enAnswer) }))}
    >
      <section className="product-download" aria-labelledby="checkvan-verification-title">
        <div><p className="eyebrow">{t('Verifica CheckVan', 'CheckVan verification')}</p><h2 id="checkvan-verification-title">{t('Controlla un documento CheckVan', 'Check a CheckVan document')}</h2><p>{t('Verifica localmente se un PDF corrisponde a un documento registrato da Driver Utility.', 'Check locally whether a PDF matches a document registered by Driver Utility.')}</p></div>
        <ButtonLink to="/verifica-checkvan">{t('Verifica documento CheckVan', 'Verify CheckVan document')}</ButtonLink>
      </section>
      <section className="product-download" aria-labelledby="checkvan-comparison-title">
        <div><p className="eyebrow">{t('Confronto CheckVan', 'CheckVan comparison')}</p><h2 id="checkvan-comparison-title">{t('Confronta due ispezioni CheckVan', 'Compare two CheckVan inspections')}</h2><p>{t('Visualizza affiancate le fotografie guidate di due ispezioni, direttamente nel browser.', 'View guided photographs from two inspections side by side, directly in your browser.')}</p></div>
        <ButtonLink to="/confronta-checkvan">{t('Confronta ispezioni CheckVan', 'Compare CheckVan inspections')}</ButtonLink>
      </section>
    </AndroidProductPage>
  )
}

export default DriverUtilityPage
