import { Navigate, Route, Routes } from 'react-router-dom'
import CheckVanComparisonPage from '../../src/pages/CheckVanComparisonPage.jsx'
import CheckVanVerificationPage from '../../src/pages/CheckVanVerificationPage.jsx'
import { AuthProvider } from './auth/AuthContext.jsx'
import AppShell from './components/AppShell.jsx'
import ProtectedRoute from './components/ProtectedRoute.jsx'
import ToolGuard from './components/ToolGuard.jsx'
import AccountPage from './pages/AccountPage.jsx'
import AssignmentsPage from './pages/AssignmentsPage.jsx'
import CheckVanPage from './pages/CheckVanPage.jsx'
import DashboardPage from './pages/DashboardPage.jsx'
import DevicesPage from './pages/DevicesPage.jsx'
import DriversPage from './pages/DriversPage.jsx'
import InspectionsPage from './pages/InspectionsPage.jsx'
import LoginPage from './pages/LoginPage.jsx'
import ToolPage from './pages/ToolPage.jsx'
import VehicleDetailPage from './pages/VehicleDetailPage.jsx'
import VehiclesPage from './pages/VehiclesPage.jsx'
import { COMPANY_ROUTES } from './routes.js'
import './styles.css'

export default function App() { return <AuthProvider><Routes><Route path="login" element={<LoginPage />} /><Route element={<ProtectedRoute deniedRoles={['UNION_GUEST']} unauthorizedRoute="/enti/verifica" />}><Route element={<AppShell />}><Route path="dashboard" element={<DashboardPage />} /><Route path="checkvan" element={<CheckVanPage />} /><Route path="ispezioni" element={<InspectionsPage />} /><Route path="veicoli" element={<VehiclesPage />} /><Route path="veicoli/:vehicleId" element={<VehicleDetailPage />} /><Route path="driver" element={<DriversPage />} /><Route path="assegnazioni" element={<AssignmentsPage />} /><Route path="pdf/verifica" element={<ToolGuard><ToolPage title="Verifica PDF"><CheckVanVerificationPage /></ToolPage></ToolGuard>} /><Route path="pdf/confronta" element={<ToolGuard><ToolPage title="Confronta ispezioni"><CheckVanComparisonPage /></ToolPage></ToolGuard>} /><Route path="dispositivi" element={<DevicesPage />} /><Route path="account" element={<AccountPage />} /></Route></Route><Route path="*" element={<Navigate to={COMPANY_ROUTES.dashboard} replace />} /></Routes></AuthProvider> }
