import { useEffect, useMemo, useState } from 'react'
import { useAuth } from '../auth/AuthContext.jsx'
import { createInspectionDownload, loadCompanyInspections } from '../lib/companySupabase.js'

const vehicle = item => item?.vehiclePlate || item?.vehicleDescription || ''
const label = item => `${new Intl.DateTimeFormat('it-IT', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(item.inspectedAt))} · Targa ${item.vehiclePlate || '—'} · Mezzo ${item.vehicleDescription || '—'} · ${item.inspectionType === 'pickup' ? 'Presa' : 'Riconsegna'}`
export default function CloudComparisonPicker({ initial = [], onReady }) {
  const { session } = useAuth(), [items,setItems]=useState([]), [first,setFirst]=useState(initial[0]||null), [second,setSecond]=useState(initial[1]||null), [slot,setSlot]=useState(null), [query,setQuery]=useState(''), [error,setError]=useState(''), [busy,setBusy]=useState(false)
  useEffect(()=>{void loadCompanyInspections(session.access_token).then(result=>setItems(result.items)).catch(()=>setItems(current=>{if(!current.length)setError('Impossibile caricare le ispezioni aziendali.');return current}))},[session.access_token])
  const choose = useMemo(()=>items.filter(item => (slot !== 'second'||(item.id !== first?.id && vehicle(item)===vehicle(first))) && `${item.vehiclePlate||''} ${item.vehicleDescription||''}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>new Date(a.inspectedAt)-new Date(b.inspectedAt)),[items,slot,first,query])
  const pick = item => { if(slot==='first'){setFirst(item);setSecond(null)}else setSecond(item);setSlot(null);setQuery('') }
  const download = async()=>{setBusy(true);setError('');try{const selected=[first,second].sort((a,b)=>new Date(a.inspectedAt)-new Date(b.inspectedAt)),files=await Promise.all(selected.map(async (item,index)=>{const position=index === 0 ? 'prima' : 'seconda';try{const {url}=await createInspectionDownload(session.access_token,item.id),response=await fetch(url);if(!response.ok)throw new Error('UNAVAILABLE');const blob=await response.blob(),signature=new TextDecoder().decode(await blob.slice(0,5).arrayBuffer()),contentType=response.headers.get('content-type')||'';if(!signature.startsWith('%PDF-'))throw new Error('NOT_PDF');return new File([blob],`checkvan-${item.id}.pdf`,{type:contentType.includes('pdf')?'application/pdf':'application/pdf'})}catch(reason){throw new Error(reason.message === 'NOT_PDF' ? `Il documento della ${position} ispezione non è un PDF valido.` : `Impossibile recuperare il PDF della ${position} ispezione.`)}}));await onReady(files,selected)}catch(reason){setError(reason.message || 'Impossibile recuperare i PDF aziendali.')}finally{setBusy(false)}}
  const card=(title,item,which)=><article className="comparison-summary"><strong>{title}</strong>{item?<span>{label(item)}</span>:<span>Nessuna ispezione selezionata</span>}<button type="button" onClick={()=>setSlot(which)}>Seleziona ispezione</button></article>
  return <section className="comparison-form"><div className="comparison-summaries">{card('ISPEZIONE PRIMA',first,'first')}{card('ISPEZIONE DOPO',second,'second')}</div>{slot&&<div className="table-card"><strong>Seleziona ispezione</strong><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Cerca targa o codice mezzo" />{choose.map(item=><button type="button" key={item.id} onClick={()=>pick(item)}>{label(item)}</button>)}</div>}<button type="button" className="button button--primary" disabled={!first||!second||busy} onClick={download}>{busy?'Caricamento ispezioni...':'Confronta ispezioni'}</button>{error&&<p className="checkvan-local-error" role="alert">{error}</p>}</section>
}
