import { useEffect, useMemo, useState } from 'react'
import { useAuth } from '../auth/AuthContext.jsx'
import { createInspectionDownload, loadCompanyInspections } from '../lib/companySupabase.js'

const vehicle = item => item.vehiclePlate || item.vehicleDescription || ''
const label = item => `${new Intl.DateTimeFormat('it-IT', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(item.inspectedAt))} · Targa ${item.vehiclePlate || '—'} · Mezzo ${item.vehicleDescription || '—'} · ${item.inspectionType === 'pickup' ? 'Presa' : 'Riconsegna'}`
export default function CloudComparisonPicker({ initial = [], onReady }) {
  const { session } = useAuth(), [items,setItems]=useState([]), [first,setFirst]=useState(initial[0]||null), [second,setSecond]=useState(initial[1]||null), [slot,setSlot]=useState(null), [query,setQuery]=useState(''), [error,setError]=useState(''), [busy,setBusy]=useState(false)
  useEffect(()=>{void loadCompanyInspections(session.access_token).then(result=>setItems(result.items)).catch(()=>setError('Impossibile caricare le ispezioni aziendali.'))},[session.access_token])
  const choose = useMemo(()=>items.filter(item => (slot==='first'||vehicle(item)===vehicle(first)) && `${item.vehiclePlate||''} ${item.vehicleDescription||''}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>new Date(a.inspectedAt)-new Date(b.inspectedAt)),[items,slot,first,query])
  const pick = item => { if(slot==='first'){setFirst(item);setSecond(null)}else setSecond(item);setSlot(null);setQuery('') }
  const download = async()=>{setBusy(true);try{const selected=[first,second].sort((a,b)=>new Date(a.inspectedAt)-new Date(b.inspectedAt)),files=await Promise.all(selected.map(async item=>{const {url}=await createInspectionDownload(session.access_token,item.id),response=await fetch(url);if(!response.ok)throw new Error();return new File([await response.blob()],`checkvan-${item.id}.pdf`,{type:'application/pdf'})}));onReady(files,selected)}catch{setError('Impossibile recuperare i PDF aziendali.')}finally{setBusy(false)}}
  const card=(title,item,which)=><article className="comparison-summary"><strong>{title}</strong>{item?<span>{label(item)}</span>:<span>Nessuna ispezione selezionata</span>}<button type="button" onClick={()=>setSlot(which)}>Seleziona ispezione</button></article>
  return <section className="comparison-form"><div className="comparison-summaries">{card('ISPEZIONE PRIMA',first,'first')}{card('ISPEZIONE DOPO',second,'second')}</div>{slot&&<div className="table-card"><strong>Seleziona ispezione</strong><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Cerca targa o codice mezzo" />{choose.map(item=><button type="button" key={item.id} onClick={()=>pick(item)}>{label(item)}</button>)}</div>}<button type="button" className="button button--primary" disabled={!first||!second||busy} onClick={download}>{busy?'Preparazione...':'Confronta ispezioni'}</button>{error&&<p className="checkvan-local-error">{error}</p>}</section>
}
